# From https://www.etiennebacher.com/posts/2021-03-19-use-github-actions-with-r-markdown-and-distill/
on:
  push:
    branches: main

name: Render & Deploy Site

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: |
          install.packages("rmarkdown")
          install.packages("tidyverse")
          install.packages('formatR', repos = 'http://cran.rstudio.com', dependencies = TRUE)
        shell: Rscript {0}

      - name: Render Book
        run: Rscript -e 'rmarkdown::render("book/Intro R for RM_DS.Rmd", "pdf_document")'
      - name: Render Site
        run: Rscript -e 'rmarkdown::render_site(encoding = "UTF-8")'
      - name: Commit results
        run: |
          git add -A
          git commit -m 'Rebuild site and book' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
